
version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: "npm-packages"
          paths:
            - src/node_modules
      - run: npm run lint
  test:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - "npm-packages"
      - run: npm i
      - run: npm run test
  analyze:
    docker:
      - image: cimg/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - "npm-packages"
      - run: npm audit

workflows:
  my-workflow:
    jobs:
      - lint
      - test:
          requires: [lint]
      - analyze:
          requires: [test]
